//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LlamaUtilities.LlamaUtilities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LlamaUtilities.LlamaUtilities.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margrat is the custom delivery NPC located in Labyrinthos..
        /// </summary>
        public static string DeliveriesSettings_MargratDescription {
            get {
                return ResourceManager.GetString("DeliveriesSettings_MargratDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nitowikwe is the custom delivery NPC located in Shaaloani..
        /// </summary>
        public static string DeliveriesSettings_NitowikweDescription {
            get {
                return ResourceManager.GetString("DeliveriesSettings_NitowikweDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open FC Workshop window..
        /// </summary>
        public static string FCWorkshop_FailedToOpenWindow {
            get {
                return ResourceManager.GetString("FCWorkshop_FailedToOpenWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCWorkshop.
        /// </summary>
        public static string FCWorkshop_Name {
            get {
                return ResourceManager.GetString("FCWorkshop_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to open FC Workshop window..
        /// </summary>
        public static string FCWorkshop_TryingToOpenWindow {
            get {
                return ResourceManager.GetString("FCWorkshop_TryingToOpenWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete ARR Daily Hunts.
        /// </summary>
        public static string HuntsSettings_ARRHuntsDescription {
            get {
                return ResourceManager.GetString("HuntsSettings_ARRHuntsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Clan Mark Daily Hunts.
        /// </summary>
        public static string HuntsSettings_ClanHuntsDescription {
            get {
                return ResourceManager.GetString("HuntsSettings_ClanHuntsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Veteran Clan Mark Daily Hunts.
        /// </summary>
        public static string HuntsSettings_VeteranClanHuntsDescription {
            get {
                return ResourceManager.GetString("HuntsSettings_VeteranClanHuntsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What stamina should we use Choco Cure at?.
        /// </summary>
        public static string RaceSettings_CureStaminaDescription {
            get {
                return ResourceManager.GetString("RaceSettings_CureStaminaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continually press left while sprinting..
        /// </summary>
        public static string RaceSettings_GoLeftDescription {
            get {
                return ResourceManager.GetString("RaceSettings_GoLeftDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continually run races until the bot is stopped..
        /// </summary>
        public static string RaceSettings_LoopDescription {
            get {
                return ResourceManager.GetString("RaceSettings_LoopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which racing course would you like to run?.
        /// </summary>
        public static string RaceSettings_RaceChoiceDescription {
            get {
                return ResourceManager.GetString("RaceSettings_RaceChoiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should we use the ability in hotbar slot 1?.
        /// </summary>
        public static string RaceSettings_UseAbility1Description {
            get {
                return ResourceManager.GetString("RaceSettings_UseAbility1Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should we use the ability in hotbar slot 2?.
        /// </summary>
        public static string RaceSettings_UseAbility2Description {
            get {
                return ResourceManager.GetString("RaceSettings_UseAbility2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desynth.
        /// </summary>
        public static string ReduceSettings_IncludeArmoryCategory {
            get {
                return ResourceManager.GetString("ReduceSettings_IncludeArmoryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Armory for desynth.
        /// </summary>
        public static string ReduceSettings_IncludeArmoryDescription {
            get {
                return ResourceManager.GetString("ReduceSettings_IncludeArmoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncludeArmory.
        /// </summary>
        public static string ReduceSettings_IncludeArmoryJsonProperty {
            get {
                return ResourceManager.GetString("ReduceSettings_IncludeArmoryJsonProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desynth.
        /// </summary>
        public static string ReduceSettings_IncludeFishCategory {
            get {
                return ResourceManager.GetString("ReduceSettings_IncludeFishCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include ALL fish for desynth.
        /// </summary>
        public static string ReduceSettings_IncludeFishDescription {
            get {
                return ResourceManager.GetString("ReduceSettings_IncludeFishDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncludeFish.
        /// </summary>
        public static string ReduceSettings_IncludeFishJsonProperty {
            get {
                return ResourceManager.GetString("ReduceSettings_IncludeFishJsonProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Coffers.
        /// </summary>
        public static string ReduceSettings_OpenCoffersDescription {
            get {
                return ResourceManager.GetString("ReduceSettings_OpenCoffersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenCoffers.
        /// </summary>
        public static string ReduceSettings_OpenCoffersJsonProperty {
            get {
                return ResourceManager.GetString("ReduceSettings_OpenCoffersJsonProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra.
        /// </summary>
        public static string ReduceSettings_StayRunningCategory {
            get {
                return ResourceManager.GetString("ReduceSettings_StayRunningCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay constantly running.
        /// </summary>
        public static string ReduceSettings_StayRunningDescription {
            get {
                return ResourceManager.GetString("ReduceSettings_StayRunningDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StayRunning.
        /// </summary>
        public static string ReduceSettings_StayRunningJsonProperty {
            get {
                return ResourceManager.GetString("ReduceSettings_StayRunningJsonProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No summoning bell near by.
        /// </summary>
        public static string Retainers_NoSummoningBell {
            get {
                return ResourceManager.GetString("Retainers_NoSummoningBell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print verbose debug info.
        /// </summary>
        public static string RetainerSettings_DebugLoggingDescription {
            get {
                return ResourceManager.GetString("RetainerSettings_DebugLoggingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrust items to retainer if the have the same item?.
        /// </summary>
        public static string RetainerSettings_DepositFromPlayerDescription {
            get {
                return ResourceManager.GetString("RetainerSettings_DepositFromPlayerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrust same items from saddle bags.
        /// </summary>
        public static string RetainerSettings_DepositFromSaddleBagsDescription {
            get {
                return ResourceManager.GetString("RetainerSettings_DepositFromSaddleBagsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t try and merge duplicate item stacks between retainers.
        /// </summary>
        public static string RetainerSettings_DontOrganizeRetainersDescription {
            get {
                return ResourceManager.GetString("RetainerSettings_DontOrganizeRetainersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdrawal Gil from each retainer.
        /// </summary>
        public static string RetainerSettings_GetGilDescription {
            get {
                return ResourceManager.GetString("RetainerSettings_GetGilDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop to continue ventures.
        /// </summary>
        public static string RetainerSettings_LoopDescription {
            get {
                return ResourceManager.GetString("RetainerSettings_LoopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reassign Ventures.
        /// </summary>
        public static string RetainerSettings_ReassignVenturesDescription {
            get {
                return ResourceManager.GetString("RetainerSettings_ReassignVenturesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affix.
        /// </summary>
        public static string Utilities_BtnAffix {
            get {
                return ResourceManager.GetString("Utilities_BtnAffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desynth.
        /// </summary>
        public static string Utilities_BtnDesynth {
            get {
                return ResourceManager.GetString("Utilities_BtnDesynth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Materia.
        /// </summary>
        public static string Utilities_BtnExtractMateria {
            get {
                return ResourceManager.GetString("Utilities_BtnExtractMateria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoTo Breeder.
        /// </summary>
        public static string Utilities_BtnGoToBreeder {
            get {
                return ResourceManager.GetString("Utilities_BtnGoToBreeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoTo Race Counter.
        /// </summary>
        public static string Utilities_BtnGoToRaceCounter {
            get {
                return ResourceManager.GetString("Utilities_BtnGoToRaceCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open All Coffers.
        /// </summary>
        public static string Utilities_BtnOpenAllCoffers {
            get {
                return ResourceManager.GetString("Utilities_BtnOpenAllCoffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce All.
        /// </summary>
        public static string Utilities_BtnReduceAll {
            get {
                return ResourceManager.GetString("Utilities_BtnReduceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Utilities_BtnRefresh {
            get {
                return ResourceManager.GetString("Utilities_BtnRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All Materia.
        /// </summary>
        public static string Utilities_BtnRemoveAllMateria {
            get {
                return ResourceManager.GetString("Utilities_BtnRemoveAllMateria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Utilities_BtnStart {
            get {
                return ResourceManager.GetString("Utilities_BtnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string Utilities_FormTitle {
            get {
                return ResourceManager.GetString("Utilities_FormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Filter.
        /// </summary>
        public static string Utilities_InventoryFilter {
            get {
                return ResourceManager.GetString("Utilities_InventoryFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choco Exp:.
        /// </summary>
        public static string Utilities_LblChocoExp {
            get {
                return ResourceManager.GetString("Utilities_LblChocoExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Bot only supports Choco Cure II, Cure III, Dash II and Super Sprint..
        /// </summary>
        public static string Utilities_LblChocoRacerInfo {
            get {
                return ResourceManager.GetString("Utilities_LblChocoRacerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;- Desynth all trust gear and possibly fish.
        /// </summary>
        public static string Utilities_LblDesynth {
            get {
                return ResourceManager.GetString("Utilities_LblDesynth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rank:.
        /// </summary>
        public static string Utilities_LblRank {
            get {
                return ResourceManager.GetString("Utilities_LblRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Materia.
        /// </summary>
        public static string Utilities_RemoveMateria {
            get {
                return ResourceManager.GetString("Utilities_RemoveMateria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affix.
        /// </summary>
        public static string Utilities_TabAffix {
            get {
                return ResourceManager.GetString("Utilities_TabAffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChocoRacer.
        /// </summary>
        public static string Utilities_TabChocoRacer {
            get {
                return ResourceManager.GetString("Utilities_TabChocoRacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Deliveries.
        /// </summary>
        public static string Utilities_TabCustomDeliveries {
            get {
                return ResourceManager.GetString("Utilities_TabCustomDeliveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Hunts.
        /// </summary>
        public static string Utilities_TabDailyHunts {
            get {
                return ResourceManager.GetString("Utilities_TabDailyHunts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FCWorkshop.
        /// </summary>
        public static string Utilities_TabFCWorkshop {
            get {
                return ResourceManager.GetString("Utilities_TabFCWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gc Turnin.
        /// </summary>
        public static string Utilities_TabGcTurnin {
            get {
                return ResourceManager.GetString("Utilities_TabGcTurnin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Housing.
        /// </summary>
        public static string Utilities_TabHousing {
            get {
                return ResourceManager.GetString("Utilities_TabHousing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Utilities_TabInventory {
            get {
                return ResourceManager.GetString("Utilities_TabInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Materia.
        /// </summary>
        public static string Utilities_TabMateria {
            get {
                return ResourceManager.GetString("Utilities_TabMateria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Utilities_TabRemove {
            get {
                return ResourceManager.GetString("Utilities_TabRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retainers.
        /// </summary>
        public static string Utilities_TabRetainers {
            get {
                return ResourceManager.GetString("Utilities_TabRetainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llama Utilities.
        /// </summary>
        public static string UtilitiesBase_Name {
            get {
                return ResourceManager.GetString("UtilitiesBase_Name", resourceCulture);
            }
        }
    }
}
